### PR TITLE
Homework 03 (Serhii Nechyporchuk)

### PR DESCRIPTION
**Pull request by serzh**

### CODE REVIEW

**Comment by vseloved** [comment]
The idea about data for the project - ok, I like it
Forum - the main part (message) is mostly missing :(
Sparql - wrong query, no real data, only metadata. Also, try to see all data for a specific person (like, Obama)
CC - I'd like to see more stats (by word, by lang, etc...)
NUCLE analysis - I liked the idea of comparing according to Levenstein's distance, but it is not what we really need: we need to count agreement on a per correction level. Very basic example:
```
Annotator1: c1, c2, c3
Annotator2: c1, c3, c4, c5
c1 & c3 match, c2, c4, c5 - don't => agreement: 2/5
```

**Comment by serzh** [comment]
Hi! Thanks for you response! I will take it to account :)
Forum. Did you mean I've done not a lot just scraping post text? If yes, I know :( Sorry, this is only I have time to do, but I've got the general idea of how to do it
Sparql. This is how I've understood the task. It states "..collect all relations...", and, as I understand and googled, the relation is just an arcs (like an mathematical relation).
CC. Yeah, don't have enough time, but get the idea 😀 
NUCLE. Sorry, I just don't get from the task that we need to measure agreement on per collection level. It just says "general and for each error type". I just realized now, that I've done only the "general" part of it. And the only thing I missed, as I understood, is to calculated distribution of agreement by error types. If this is the case, I can add this metric using same levenstein distance, but restrict errors to only one type. 

You haven't commented my wiktionary task. I'm just worrying, is it fine? 😨

**Comment by vseloved** [comment]
Wiktionary is fine :)
Sparql: yes, relations are just arcs, but they also point to properties. The interesting part is to collect properties, like: born at <some date>, married to <someone> etc., not just the names of the relations. Sorry, this is underspecification of the task :)
NUCLE: the main point is to compare objects

**Comment by serzh** [comment]
Don't get the point about NUCLE. Don't you mind  to discuss it tomorrow?

**Comment by vseloved** [comment]
sure

**Comment by vseloved** [comment]
Нужно разделить на 2 PR-а: hw3 и hw4, потому что не могу смерджить 3-ю.
По третьей оценка: 5+5+20+10+0+15+5=60

**Comment by serzh** [comment]
Да, сори, пофикшу

**Comment by serzh** [comment]
fixed

**Pull request merged**
