### PR TITLE
Complete task 03 nlp data

### PR DESCRIPTION
**Pull request by sudodoki**

### CODE REVIEW

**Comment by vseloved** [comment]
TODO: gzip all big files

1. Wiktionary - it would be nice to filter by article language (there should be a marker like `==English==`) as there are non-bg words. But ok :)
2. NUCLE: where there any conclusions? 
3. Scraping - ok
4. CC - word cloud is useful here, but it would also be cool to also see the breakdown by language, text length etc. Also readability...
5. Sparql - is that all?

**Comment by sudodoki** [comment]
Updated 1/2/4 according to comments. Didn't run readability on raw html to extract text as it takes forever 😱 

>Sparql - is that all?

I assume this is the whole query that will get all the persons and all their relations, but I'm no expert here :) I didn't put whole output to file, only few results, in case you meant the size of result.

**Comment by vseloved** [comment]
> I assume this is the whole query that will get all the persons and all their relations

Can you take someone (like Obama) and post all the data that you can collect on him?

Another question: what about the data for the project?

**Comment by sudodoki** [comment]
>Can you take someone (like Obama) and post all the data that you can collect on him?

```
SELECT ?person ?relates ?to
WHERE {
  BIND (<http://dbpedia.org/resource/Barack_Obama> AS ?person)
  ?person a foaf:Person .
  ?person dbo:relation ?to .
  ?person ?relates ?to .
  FILTER ( ?relates != dbo:relation ) .
}
```
Would yield empty results back, nobody marked any relations as dbo:relation for this entity.
If I relax `?person dbo:relation ?to .` I get a bunch of extra stuff I don't think useful in this case like

person | relates | to
-- | -- | --
:Barack_Obama | rdf:type | owl:Thing
:Barack_Obama | rdf:type | foaf:Person
:Barack_Obama | rdf:type | dbpedia:ontology/Person
:Barack_Obama | rdf:type | <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#Agent>
:Barack_Obama | rdf:type | <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#NaturalPerson>
:Barack_Obama | rdf:type | <http://www.wikidata.org/entity/Q215627>
:Barack_Obama | rdf:type | <http://www.wikidata.org/entity/Q24229398>

and if I add `  ?to a foaf:Person .` as a constraint I will get

person | relates | to
-- | -- | --
:Barack_Obama | dbpedia:ontology/successor | :Kwame_Raoul
:Barack_Obama | dbpedia2:predecessor | :Alice_Palmer_(politician)
:Barack_Obama | dbpedia2:parents | :Barack_Obama_Sr.
:Barack_Obama | dbpedia:ontology/spouse | :Michelle_Obama
:Barack_Obama | dbpedia:ontology/successor | :Roland_Burris
:Barack_Obama | dbpedia2:parents | :Ann_Dunham
:Barack_Obama | dbpedia2:predecessor | :Peter_Fitzgerald_(politician)
:Barack_Obama | dbpedia2:predecessor | :George_W._Bush
:Barack_Obama | dbpedia:ontology/vicePresident | :Joe_Biden

Is this good enough?

>Another question: what about the data for the project?

So far I have identified some articles doing research in same domain and working through them to find related datasets / tools / approaches.

Two datasets I'm considering useful so far are

- http://www.cs.columbia.edu/nlp/tools.cgi#Quoted%20Speech%20Attribution%20Corpus
- https://github.com/dbamman/characterRelations

Another possible source would be RDF's from DBPedia as noted in oner article, in regards to
1) fictional character & alternative names (will require additional cleaning up)
```
SELECT ?person ?relation ?to
WHERE {
  ?person a dbo:FictionalCharacter .
  ?person ?relation ?to
  FILTER (?relation = rdfs:label 
          || ?relation = rdfs:comment 
          || ?relation = rdfs:seeAlso 
          || ?relation = owl:sameAs 
          || ?relation = foaf:name 
          || ?relation = foaf:surname 
          || ?relation = foaf:nick 
          || ?relation = <http://dbpedia.org/ontology/alias> 
          || ?relation = foaf:givenName 
          || ?relation = dbpedia2:name 
          || ?relation = dbpedia2:aliases 
          || ?relation = dbpedia2:realName ).
}
```
2) fictional characters & relations (should extend based on additional relations listed on http://mappings.dbpedia.org/server/ontology/classes/Person)
```
SELECT ?person ?relation ?to
WHERE {
  ?person a dbo:FictionalCharacter .
  ?person ?relation ?to . 
  FILTER (
  ?relation = dbpedia2:allies ||
  ?relation = dbpedia2:groups ||
  ?relation = dbpedia2:alliances ||
  ?relation = dbpedia2:affiliation  ||
  ?relation = dbpedia2:grouping ||
  ?relation = dbpedia2:hero ||
  ?relation = dbpedia2:homeworld ||
  ?relation = dbpedia2:offspring ||
  ?relation = dbpedia2:status ||
  ?relation = dbpedia2:subGrouping ||
  ?relation = dbpedia2:subcat ||
  ?relation = dbpedia2:symbol ) .
}
LIMIT 100
```

Other possible data sources
I. getting short text, annotating relations mentioned in those and using full text to match. For dataset here could use
- scrapping http://www.sparknotes.com (http://www.sparknotes.com/shakespeare/macbeth/)
- https://www.amazon.com/Major-Characters-American-Fiction-Reference/dp/0805045643/ref=sr_1_1?ie=UTF8&qid=1334174229&sr=8-1
- http://www.cs.cmu.edu/~dbamman/booksummaries.html
Might be interesting to match texts and RDF acquired from DBPedia to fasten the annotation.

II. characters relations that would probably be scraped from wiki like pages
- https://tools.wmflabs.org/reasonator/?&q=208255
- http://imagecomics.wikia.com/wiki/Category:Characters
- http://dc.wikia.com/wiki/Category:Characters
- http://whatcharacter.com/
- http://marvel.com/characters
- https://www.willjordanbooks.co.uk/character-database/
- https://www.obvibase.com/p/N7SD6v1F4mrVBWzV#table/N7SD6v1F4mrVBWzV/*
- http://www.whoaisnotme.net/cdb/characters.htm
- https://www.wattpad.com/303176628-character-database-alyssa-thomas
- https://www.superherodb.com/
- https://www.opensourceshakespeare.org/views/plays/characters/char_search.php / https://www.opensourceshakespeare.org/
- http://www.finalfantasyunion.com/characters/
- http://www.sowhowins.com/characterdatabasea.htm
- https://www.vinceflynn.com/search-character-database/
- https://www.hp-lexicon.org/characters/

**Comment by vseloved** [comment]
Obama - it's much better, it would be cool to see all different dbpedia properties, not only `dbo:relation`s.

There's also [Wookiepedia](http://starwars.wikia.com) :)

re NUCLE: I see quite different numbers in others' results, like maximum (regardless of error type and correction) agreement <50%. We'll compare that on Sat...

**Comment by vseloved** [comment]
5+15+18+20+5+15+5=83%

**Comment by sudodoki** [comment]
>Obama - it's much better, it would be cool to see all different dbpedia properties, not only dbo:relations.

Oh, I tried getting all the relations that are under`dbo:relation` because those seemed most meaningful to me but filtered to not get `dbo:relation` back. Would be glad to hear on Sat what was the preferred way to do this.

**Pull request merged**
