### PR TITLE
vikua/task 3 solution 

### PR DESCRIPTION
**Pull request by vikua**
Task 3 solution 
@vseloved

### CODE REVIEW

**Comment by vseloved** [comment]
- CC: good job, the only thing I don't understand is why some words appear several times in the world cloud (it: 'da'), and some frequent words don't appear (en: there's no 'the')?
- forum: trying to get output file - AccessDenied
- dbpedia: can I see all available info on a specific person, for example, Obama?
- NUCLE: very small numbers for agreement, can you explain how they are calculated: i.e. what is `total_len`/`common_len` and why are they so big?
- what about the ideas for the project?

**Comment by vikua** [comment]
- lviv forum: oops, forgot to allow public read access, can you please try again?

**Comment by vseloved** [comment]
Works now. Also, it would be cool to also remove HTML formatting and add a couple more fields (date of post), but ok.

**Comment by vikua** [comment]
- NUCLE:
I think the agreement is so low because I use very simple heuristic to check whether corrections are same. For example to compute general error agreement each error is represented as `"doc_id:start_paragraph:end_paragraph:start_offset:end_offset:type:correction"` string (string identifier of error changes depending on whether it is general, per doc or per error agreement). 
`total_len` is total number of unique errors found by all teachers, `common_len` is number of common  errors (intersection) found by each teacher. As far as I can see from dataset, if we consider all features and use heuristic when all of them should match exactly - we get quite low agreement, because different teaches can make different corrections for same start_offset/end_offset pair.

I think if I used more sophisticated heuristic, like checking an intersection of offsets instead of exact match, checking distance between corrections - agreement would become higher.

**Comment by vikua** [comment]
CC:
I bet something wrong with tokenizer, will check

**Comment by vikua** [comment]
Btw, regarding `the` in word cloud - barplot for English says the is the most common
http://prntscr.com/iv8wxb

Maybe I messed up with word cloud computation

**Comment by vikua** [comment]
Oh, looks like the `wordcloud` lib I use is smart enough to use some `default` list of stop words

```
 |  stopwords : set of strings or None
 |      The words that will be eliminated. If None, the build-in STOPWORDS
 |      list will be used.
```

**Comment by vikua** [comment]
It makes sense, as `de` (pt and es) , which is analog of `the` I suppose, is not eliminated for other languages

**Comment by vseloved** [comment]
regarding 'the' - yes, that's what I noticed
regarding NUCLE: ok, I agree

**Comment by vikua** [comment]
regarding word cloud: I do no see duplicated `da` in Italian, but I do see duplicated `di`

http://prntscr.com/iv9hsv

I've taken only Italian texts and tried to find wordcloud tokens 

```
it = df[df['lang'] == 'it'].fillna('')
wordcloud = WordCloud()
text = it['words'].str.cat(sep=' ')
d = wordcloud.process_text(text)
d = sorted(d.items(), key=lambda x: x[1], reverse=True)
```

result is 

```
[('di', 4541),
 ('che', 3058),
 ('per', 2005),
 ('da', 1991),
 ('con', 1560),
 ('del', 1512),
 ('per la', 1408),
 ('Wed Feb', 1321),
 ('ma', 1181),
 ('al', 1115),
 ('come', 1018),
 ('de', 1016),
 ('un', 1011),
 ('più', 983),
 ('anche', 980),
 ('nel', 927),
 ('per il', 883),
 ('non', 834),
 ('Coppa Italia', 763),
 ('di un', 749),
 ('con la', 668),
```

so it is not `di` but `di un`. 
This is weird, looks like wordcloud couldn't tokenize some some bigrams like `con la`, `per il` correctly. 
If I just take the text and try to split it with whitespace, it splits them correctly 

```
unique = set(text.split())
[x for x in unique if x == 'con la' or x == 'di un']
out: []
```

**Comment by vikua** [comment]
May be it tries to be smarter again and recognizes `di un` as single token (like with Coppa Italia), need to dig deeper to figure out

**Comment by vikua** [comment]
Regarding project data - I'm working on it :(
Just was trying to get tasks done by Thursday

**Comment by vikua** [comment]
Regarding dbpedia Obama query, following works:

```
 SELECT ?name2 ?relationship ?name1 where {
    ?person1 a foaf:Person .
    ?person2 a foaf:Person .
    ?person1 dbo:relation ?person2 .
    ?person1 ?relationship ?person2 .
    ?person1 foaf:name ?name1 .
    ?person2 foaf:name ?name2 .
    filter (?person2 = <http://dbpedia.org/resource/Barack_Obama>)
 }
```

But returns limited number of relations 

```
name2	relationship	name1
"Barack Obama"@en	dbpedia:ontology/relation [http]	"Stanley Armour Dunham"@en
"Barack Obama"@en	dbpedia:ontology/relation [http]	"Maya Soetoro-Ng"@en
"Barack Obama"@en	dbpedia:ontology/relation [http]	"Marian Shields Robinson"@en
"Barack Obama"@en	dbpedia:ontology/relation [http]	"Charles T. Payne"@en
"Barack Obama"@en	dbpedia:ontology/relation [http]	"Charles Thomas Payne"@en

```

**Comment by vikua** [comment]
Please ignore previous, this is way better: 

```
SELECT DISTINCT ?has ?of ?person 
WHERE {

{?person a foaf:Person; 
?of dbr:Barack_Obama} 

UNION

{?person a foaf:Person. 
dbr:Barack_Obama ?has ?person}

}
```

First results: 

```

has | of | person
-- | -- | --
- | dbpedia:ontology/president | :Melody_Barnes
- | dbpedia:ontology/president | :Michael_T._Flynn
- | dbpedia:ontology/president | :Mythili_Raman
- | dbpedia:ontology/president | :David_Hale_(diplomat)
- | dbpedia:ontology/president | :David_McKean_(diplomat)
- | dbpedia:ontology/president | :Janet_Napolitano
- | dbpedia:ontology/president | :Janet_Yellen
- | dbpedia:ontology/president | :John_Kirby_(admiral)
- | dbpedia:ontology/president | :Matthew_Barzun
- | dbpedia:ontology/appointer | :Nancy_Moritz
- | dbpedia:ontology/president | :Adrienne_Thomas
- | dbpedia:ontology/president | :Aneesh_Chopra
- | dbpedia:ontology/president | :Anthony_W._Miller
- | dbpedia:ontology/president | :Daniel_Poneman
- | dbpedia:ontology/president | :Jamie_M._Morin
- | dbpedia:ontology/president | :Jeffrey_L._Bleich
- | dbpedia:ontology/president | :Jim_Messina_(political_staffer)
- | dbpedia:ontology/president | :Julius_Genachowski
- | dbpedia:ontology/president | :Matthew_G._Olsen
- | dbpedia:ontology/president | :Mona_Sutphen
- | dbpedia:ontology/knownFor | :Orly_Taitz
- | dbpedia:ontology/president | :Rosa_Gumataotao_Rios
- | dbpedia:ontology/president | :Timothy_Geithner
- | dbpedia:ontology/president | :Todd_Stern
- | dbpedia:ontology/president | :W._Scott_Gould
- | dbpedia:ontology/appointer | :John_W._deGravelles



```

**Comment by vikua** [comment]
Is it ok? 

Regarding course project data, I'm planing to scrap news sites (http://pravda.com.ua, http://censor.net.ua, http://unian.ua, http://tsn.ua/) and will be keeping it in separate git hub repository. 

I also have an idea to add a couple of sources, which are very subjective in terms of political news (like vesti), but not sure whether it will add value, as 
1) I add my own bias here (not all people think some resources like vesti are subjective)
2) It still doesn't help to identify relationships between who is subjective and who is a subject of that subjectivity (like somebody expresses his own option regarding political figure or situation)
3) doesn't help to identify subjective phrases. 

I think I'll use an ensemble of approaches to annotate the data for subjectivity. It will be required to annotate some articles manually and find a pattern, like assumptions, emotional phrases, so that it is possible to build some kind of rule based annotation approach. 
Also may be it is worth analyzing sentiments, as I believe negative sentiment tend to be more subjective (usually).  Not sure about crowdsourcing, though. 

Anyway, I'm still struggling on how to better annotate raw text and what semi-supervised and unsupervised techniques to use.

**Comment by vseloved** [comment]
Оценка: 5+20+20+20+5+20+5=95

**Comment by vikua** [comment]
🎉

**Pull request merged**
